'use strict';

const Types = {
  RETRIEVE_USER: 'RETRIEVE_USER',
  RETRIEVED_USER: 'RETRIEVED_USER',
  LIST_USERS: 'LIST_USERS',
  RETRIEVED_LIST_USERS: 'RETRIEVED_LIST_USERS',
  CREATE_USER: 'CREATE_USER',
  CREATED_USER: 'CREATED_USER',
  UPDATE_USER: 'UPDATE_USER',
  UPDATED_USER: 'UPDATED_USER',
  DELETE_USER: 'DELETE_USER',
  DELETED_USER: 'DELETED_USER',
  LOG_OUT: 'LOG_OUT',
};

export default Types;
